### ISSUE TITLE
Can't retrieve Directions or Geocode when using ProGuard

### ISSUE THREAD

**Issue by dadino** [googlemaps/google-maps-services-java#102]
When using **Proguard** I can't retrieve Geocoding or Directions using this library. I can't find Proguard's rules for this library.

This is what I get when trying to **Geocode**:

    com.google.maps.a.h: An unexpected error occurred. Status: null, Message: null
    at com.google.maps.f.c(GeocodingApi.java:84)
    at com.google.maps.b.i.a(OkHttpPendingResult.java:236)
    at com.google.maps.b.i.onResponse(OkHttpPendingResult.java:183)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

And this is for **Directions**:

    com.google.maps.a.h: An unexpected error occurred. Status: null, Message: null
    at com.google.maps.b.c(DirectionsApi.java:69)
    at com.google.maps.b.i.a(OkHttpPendingResult.java:236)
    at com.google.maps.b.i.onResponse(OkHttpPendingResult.java:183)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

I have warnings about **YodaTime**, I tried with
 
    -keep class org.joda.** { *; }

and

    -dontwarn org.joda.convert.**
But it isn't working.

**Comment by domesticmouse** [comment]
This library was not designed for use on Android, as third parties can steal your API Key by disassembling your APK. I'd suggest you look at introducing a server component that stores your API key and maybe does some of your application logic, reducing the amount of data that has to be downloaded by your customer's phones.

As a simplistic starting point, feel free to try out https://github.com/domesticmouse/places-api-key-proxy

**Comment by dadino** [comment]
I suggest pointing it out on the read me, since it works perfectly when Proguard is not enabled I (and maybe others) counted on this to work in production.

**Comment by amitsri20** [comment]
@domesticmouse I didn't get the use case here for Geo location API, as when I am using API with no progaurd rules and minifyDisabled then it's working even in release build. If rule is made to secure application then it should be applicable in every case?

**Comment by domesticmouse** [comment]
@amitsri20 as I previously mentioned in https://github.com/googlemaps/google-maps-services-java/issues/102#issuecomment-143390632 this library is not designed to ship as part of an Android app due to API Key theft issues.

**Comment by MuhamedFathy** [comment]
Try this in your `proguard-rules.pro`.
    
    -keep class com.google.maps.** { *; }
