### ISSUE TITLE
Set retry limit to lower value

### ISSUE THREAD

**Issue by frapontillo** [googlemaps/google-maps-services-java#105]
I am extensively using the Geocoding API for a uni project (~ 30000 requests per day), and I often see these kind of exceptions:

```
INFO: Request: https://maps.googleapis.com/maps/api/geocode/json?key=mykey&address=Some+address
Sep 30, 2015 5:42:04 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #1
Sep 30, 2015 5:42:04 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #2
Sep 30, 2015 5:42:05 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #3
Sep 30, 2015 5:42:07 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #4
Sep 30, 2015 5:42:10 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #5
Sep 30, 2015 5:42:12 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #6
Sep 30, 2015 5:42:16 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #7
Sep 30, 2015 5:42:20 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #8
Sep 30, 2015 5:42:29 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #9
Sep 30, 2015 5:42:45 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #10
Sep 30, 2015 5:42:58 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #11
com.google.maps.errors.UnknownErrorException
	at com.google.maps.errors.ApiException.from(ApiException.java:50)
	at com.google.maps.GeocodingApi$Response.getError(GeocodingApi.java:84)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:236)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:263)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:194)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)
	at com.my.package.MyClass$1.getCoordinates(MyClass.java:70)
	...
```

I can see why you repeat the request for `n` times, but I'd like to lower that threshold, as it freezes my pipeline for too long. I have also noticed that when errors are repeated for more than 2-3 times, it's probably due to some server error that doesn't fix itself in the next attempts (i.e. my requests are always attempted 1 or 11 times).

Is there a way to lower the retry quantity?

**Comment by markmcd** [comment]
It's not quite what you're asking, but you can set the retry timeout to a lower number using [setRetryTimeout](http://googlemaps.github.io/google-maps-services-java/v0.1.7/javadoc/com/google/maps/GeoApiContext.html#setRetryTimeout(long,%20java.util.concurrent.TimeUnit))

**Comment by frapontillo** [comment]
That is good enough for me, thank you! :+1:
