### ISSUE TITLE
Thread State WATING (parking) on com.google.maps.internal.RateLimitExecutorService

### ISSUE THREAD

**Issue by mitobit** [googlemaps/google-maps-services-java#109]
Hi,
We are using google-maps-services library (v. 0.1.7) in production enviroments and we discovered to much thread "opened" in our JVMs.

We did a thread dump and we find out the a lot of Thread  (200)  in the following situation:
```
"Thread-51224" daemon prio=10 tid=0x00007f8e6c32d000 nid=0x1b6e waiting on condition [0x00007f8eddbea000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000786ea7638> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.google.maps.internal.RateLimitExecutorService.run(RateLimitExecutorService.java:88)
	at java.lang.Thread.run(Thread.java:745)
```
We have very very few traffic on our application. (Some requests for days)

Can you help us to understand the issue?

Regards

**Comment by mitobit** [comment]
Please find below the two pieces of code used in our application
```
GeoApiContext context = new GeoApiContext().setApiKey(Configuration.GOOGLE_API_KEY);
GeocodingResult[] results = GeocodingApi.newRequest(context).language("IT").components(ComponentFilter.locality("Roma")).address(geoRequest.getAddress()).await();
if (results != null){
//Read results
}
```


```
GeoApiContext context = new GeoApiContext().setApiKey(Configuration.GOOGLE_API_KEY);
GeocodingResult[] results = null;
results = GeocodingApi.newRequest(context).language("IT").place(geoRequest.getPlaceId()).await();
if (results != null && results.length != 0){
//Read results
}
```

**Comment by eRfO** [comment]
You have to use the same instance of GeoApiContext for each request, otherwise it will be created a new instance of RateLimitExecutorService that starts a new thread deamon every time.

**Comment by markmcd** [comment]
That's correct - the context is meant to be created once per application (though there are some exceptions), as it handles things like rate limiting that require state to persist between requests.

**Comment by sbojchuk** [comment]
Hello, I have faced the same issue, this helped me. Thanks.
