### ISSUE TITLE
NearbySearchRequest followed by PlaceDetailsRequest

### ISSUE THREAD

**Issue by xavierxc14** [googlemaps/google-maps-services-java#149]
Hi,
I get this Exception:
```java
java.lang.IllegalStateException: 'await', 'awaitIgnoreError' or 'setCallback' was already called.
at com.google.maps.PendingResultBase.makeRequest(PendingResultBase.java:74)
at com.google.maps.PendingResultBase.await(PendingResultBase.java:55)
```
I don't understand why, and I would really appreciate if someone could explain me and give me a hint on what can I do to solve it?

**Comment by xavierxc14** [comment]
Solved:
http://stackoverflow.com/questions/36775172/exception-using-google-maps-services-java-on-await
