### ISSUE TITLE
Speed limits are not available for this project.

### ISSUE THREAD

**Issue by bigbansal** [googlemaps/google-maps-services-java#178]
Hello Team,

I am trying to use RoadsAPI. Using a test case, 

Code I have written is : 

 SnappedSpeedLimitResponse response = RoadsApi.snappedSpeedLimits(context,
		                new LatLng(-33.865382, 151.192861),
		                new LatLng(-33.865837, 151.193376),
		                new LatLng(-33.866745, 151.19373),
		                new LatLng(-33.867128, 151.19344),
		                new LatLng(-33.867547, 151.193676),
		                new LatLng(-33.867841, 151.194137),
		                new LatLng(-33.868224, 151.194116)).await();

and exception I am getting is : 
Exception in thread "main" com.google.maps.errors.RequestDeniedException: Speed limits are not available for this project.
	at com.google.maps.errors.ApiException.from(ApiException.java:65)
	at com.google.maps.RoadsApi$CombinedResponse.getError(RoadsApi.java:187)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:270)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:167)
	at com.google.maps.nomad.DirectionApiProgram.main(DirectionApiProgram.java:145)

Thanks & Regards,
BBansal

**Comment by domesticmouse** [comment]
This is not an issue with the Google Maps Web Services client library, rather it is an access issue with your API project.

According to [the API documentation](https://developers.google.com/maps/documentation/roads/speed-limits) the speed limit service is available only to Google Maps APIs Premium Plan customers with an Asset Tracking license.

**Comment by alaminprogramerr** [comment]
https://guides.github.com/features/mastering-markdown/
