### ISSUE TITLE
Unable to use Proxy with Authentication for encoding requests

### ISSUE THREAD

**Issue by ja-fra** [googlemaps/google-maps-services-java#190]
Hi,

I'm not able to get geocoding request work via a Proxy that requires Authentication. However, requests over an open Proxy do work as expected.

```
Caused by: java.net.ProtocolException: Unexpected status line: <html>
    at com.squareup.okhttp.internal.http.StatusLine.parse(StatusLine.java:54)
    at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
    at com.squareup.okhttp.internal.io.RealConnection.createTunnel(RealConnection.java:270)
    at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:172)
    at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
    at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
    at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
    at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
    at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
    at com.squareup.okhttp.Call.getResponse(Call.java:286)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
    at com.squareup.okhttp.Call.access$100(Call.java:35)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Proxy- and Authentication Proxy settings are correct and do work for other connections (not via the maps-sdk), e.g:

```
final HttpURLConnection connection = (HttpURLConnection) new URL("https://maps.googleapis.com/").openConnection(proxy);
connection.setRequestMethod("GET");
connection.connect();
Assume.assumeThat("ping failed", connection.getResponseCode(), Matchers.allOf(Matchers.greaterThanOrEqualTo(200), Matchers.lessThan(300)));
```

Any hints where to look? I'm aware of #141 and my implementation is based on the recommendations there...

Thanks,
Jakob

**Comment by domesticmouse** [comment]
Given that stack trace, the first place I'd look is at the OkHttp documentation. If you can find the right setting that needs to be tweaked in OkHttp, then we can expose that setting through the context constructor. Thanks!

**Comment by domesticmouse** [comment]
Closing this out. Please re-open if you investigate further. Thanks!
