### ISSUE TITLE
Geocoding API | UnknownErrorException

### ISSUE THREAD

**Issue by anoopsin** [googlemaps/google-maps-services-java#216]
Stack trace:

```
! com.google.maps.errors.UnknownErrorException: null
! at com.google.maps.errors.ApiException.from(ApiException.java:55)
! at com.google.maps.GeocodingApi$Response.getError(GeocodingApi.java:81)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:279)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:292)
! at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:218)
! at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:175)
! at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)
```

To reproduce, specify address as: `fhfdghfyg+2%2C12456%2Csfdgygfdyg%2Cfdgsffydh%2CGermany`

Strangely, it succeeds if you omit the first `f`: `hfdghfyg+2%2C12456%2Csfdgygfdyg%2Cfdgsffydh%2CGermany`

This was noticed on Dec 7, 17:00 PST.

Surprisingly, I tried it the next day, Dec 8, 10:32 PST and it works fine.

**Comment by domesticmouse** [comment]
I'm really unsure what you did here. I'm guessing this is now working as intended, but in future cases could you please create a gist that demonstrates a reduced sample case that fails? I really need the underlying API call that is causing the failure to be able to chase up with the API team. It looks to me like they generated an invalid response and confused OkHttp in the process.
