### ISSUE TITLE
ClassNotFoundException okhttp

### ISSUE THREAD

**Issue by machielg** [googlemaps/google-maps-services-java#225]
I can't use the library in my maven project. Is there anything obvious I'm missing?

I've created a new maven project with only this dependency:
```
<dependency>
  <groupId>com.google.maps</groupId>
  <artifactId>google-maps-services</artifactId>
  <version>0.1.17</version>
</dependency>
```

When I try to create a GeoApiContext it fails loading the okhttp classes:

```
java.lang.NoClassDefFoundError: com/squareup/okhttp/MediaType
	at com.google.maps.OkHttpRequestHandler.<clinit>(OkHttpRequestHandler.java:43)
	at com.google.maps.GeoApiContext.<init>(GeoApiContext.java:88)
	at test.Test.test(Test.java:9)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.MediaType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
```

**Comment by machielg** [comment]
Sorry, the okhttp jar file didn't download properly the first time.
