### ISSUE TITLE
invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by chongma** [googlemaps/google-maps-services-java#262]
hi, 
when i include google-maps-services into my project with maven
```
<dependency>
	<groupId>com.google.maps</groupId>
	<artifactId>google-maps-services</artifactId>
	<version>0.1.20</version>
</dependency>
```
it compiles fine.  but when i try to start the container (TomEE 7.0.2) it gives me a bad signature on the jar file.
```
21-Apr-2017 10:11:02.890 SEVERE [Catalina-startStop-1] sun.reflect.NativeMethodAccessorImpl.invoke A child container failed during start
 java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rest]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:911)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:890)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rest]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@7f6bd5b6]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4842)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4974)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@6bff3f18]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:708)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 9 more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:113)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	... 12 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.IOUtils.readFully(IOUtils.java:65)
	at java.util.jar.JarFile.getBytes(JarFile.java:425)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:111)
	... 13 more
```
i don't have any problems with any other dependencies.  i have tried cleaning out the .m2 directory but it results in the same error.  only affecting this package

**Comment by chongma** [comment]
hi, i have just packaged the project myself and it works fine.  are you sure you are not distributing with a damaged package inside?  one of your dependencies may be broken in your local maven repository.  try cleaning and repackaging.

**Comment by chongma** [comment]
hmmm....when i try to run
```
GeoApiContext context = new GeoApiContext(new GaeRequestHandler()).setApiKey(googleMapsKey);
```
i get 
```
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: java.lang.NoClassDefFoundError: com/google/appengine/api/urlfetch/URLFetchServiceFactory
```

**Comment by chongma** [comment]
if i exclude okhttp it allows container to start
```
<dependency>
    <groupId>com.google.maps</groupId>
    <artifactId>google-maps-services</artifactId>
         <version>0.1.20</version>
         <exclusions>
             <exclusion>
		<groupId>com.squareup.okhttp</groupId>
		<artifactId>okhttp</artifactId>
	    </exclusion>
	</exclusions>
</dependency>
```
and i can avoid the appengine error if i add the dependency
```
<dependency>
	<groupId>com.google.appengine</groupId>
	<artifactId>appengine-api-1.0-sdk</artifactId>
	<version>1.9.51</version>
</dependency>
```
but then i get an error
```
com.google.maps.errors.UnknownErrorException: Unexpected exception from com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
```

**Comment by chongma** [comment]
if i try to use asynchronous instead of synchronous i get
```
Caused by: java.lang.RuntimeException: setCallback not implemented for Google App Engine
	at com.google.maps.internal.GaePendingResult.setCallback(GaePendingResult.java:105)
	at com.google.maps.PendingResultBase.setCallback(PendingResultBase.java:52)
	at uk.me.kissy.rest.dao.PopulationDao.updateLatLng(PopulationDao.java:583)
	at uk.me.kissy.rest.dao.PopulationDao.selectPopulations(PopulationDao.java:460)
	at uk.me.kissy.rest.dao.PopulationDao$$OwbNormalScopeProxy0.selectPopulations(uk/me/kissy/rest/dao/PopulationDao.java)
	at uk.me.kissy.rest.beans.PopulationsBean.update(PopulationsBean.java:28)
	at uk.me.kissy.rest.beans.PopulationsBean.onload(PopulationsBean.java:24)
	at uk.me.kissy.rest.beans.PopulationsBean$$OwbNormalScopeProxy0.onload(uk/me/kissy/rest/beans/PopulationsBean.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
	... 41 more
```

**Comment by chongma** [comment]
ok it seemed that com.squareup.okio was jammed on my local machine.  but i still get the same error as in the previous comment

**Comment by domesticmouse** [comment]
I'm confused as to what you are attempting to accomplish. Do you want to put together a minimised reproduction case as a github repo so I can reproduce the problems you are seeing?

**Comment by chongma** [comment]
you are confused as to what i am trying to accomplish?  i am adding the library to my project and trying to follow the example in the README.

i have now added the library successfully after having a problem with okio (a dependency of okhttp) being jammed.  FYI it had imported into my Maven a sources version of 1.6.0 which was corrupted.

the first error is
```
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: java.lang.NoClassDefFoundError: com/google/appengine/api/urlfetch/URLFetchServiceFactory
```
which can be solved by adding the dependency
```
<dependency>
	<groupId>com.google.appengine</groupId>
	<artifactId>appengine-api-1.0-sdk</artifactId>
	<version>1.9.51</version>
</dependency>
```
i notice that in your `build.gradle` you have `appengine-api-1.0-sdk` as compileOnly so maybe it is not included as a dependency in the pom?

at this point i can start the container (TomEE 7.0.2) but when i try to run synchronously
```
GeocodingResult[] geocodingResultArray = req.await();
``` 
i get this error
``` 
com.google.maps.errors.UnknownErrorException: Unexpected exception from com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
```
and if i try to run asynchronously
```
req.setCallback(new PendingResult.Callback<GeocodingResult[]>()
```
i get
```
Caused by: java.lang.RuntimeException: setCallback not implemented for Google App Engine
```
i can build a reproducer or you could try running your example on TomEE 7.0.2?

**Comment by chongma** [comment]
if i go back to `google-maps-service` version `0.1.10` then `import com.google.maps.GaeRequestHandler;` is not available in the package so the example cannot be used.

**Comment by domesticmouse** [comment]
Honestly, it's been the best part of a decade since I last used a EE container, so I'd have to do a lot of reading to get to the point of having something that probably resembles the use case you are attempting to get to work. It would help me if you would put together a minimised reproduction case as a Github repo that I could clone, add a key to, and start debugging.

**Comment by chongma** [comment]
the EE container is a red herring because i get exactly the same results with a standard maven project.  https://github.com/chongma/testGoogleMapsServices

**Comment by chongma** [comment]
i created the test project.  did you look at it?  the App class has a main function so you should be able to run it from there.  in the pom.xml it includes the extra dependency
```
<dependency>
	<groupId>com.google.appengine</groupId>
	<artifactId>appengine-api-1.0-sdk</artifactId>
	<version>1.9.51</version>
</dependency>
```
as it wouldn't run without it

**Comment by chongma** [comment]
hi, sorry for chasing.  not sure if you got my previous messages?

**Comment by domesticmouse** [comment]
First question of the day, why are you using Google App Engine jars outside of Google App Engine?

**Comment by chongma** [comment]
i am trying to access the google maps service from a java server.  google maps had a link to your project saying it was a java client to the google maps service.

**Comment by chongma** [comment]
![2017-04-26-12 12 05-pm](https://cloud.githubusercontent.com/assets/6253322/25429618/e4e8baf4-2a79-11e7-82ec-9b158807b9c3.png)

**Comment by chongma** [comment]
i have provided you with a basic maven project which includes your library as a dependency but i cannot make a request due to the errors outlined in my previous comments.  am i doing something wrong?

**Comment by domesticmouse** [comment]
Sorry about the delay, kinda busy getting ready for I/O

**Comment by chongma** [comment]
ok i see now.  i was using the wrong code...  must have been drawn by the asynchronous bit...

**Comment by chongma** [comment]
thanks for your help and good luck with I/O

**Comment by domesticmouse** [comment]
All good, hopefully my pull request is enough to get you moving. Btw, you don't want to use `req.await()` in a server context, as it will tie up the thread. Use the callbacks instead. Thanks!

**Comment by rsoffer** [comment]
@chongma I'm experiencing the same exact issues. I'm stuck on `Caused by: java.lang.RuntimeException: setCallback not implemented for Google App Engine`

How did you resolve this? Thanks!

**Comment by chongma** [comment]
@rsoffer there is a test project here https://github.com/chongma/testGoogleMapsServices which @domesticmouse amended for me.  basically you should be using the example further up the page and not the google app engine one.

**Comment by chongma** [comment]
this one i think
```
GeoApiContext context = new GeoApiContext().setApiKey("AIza...");
GeocodingResult[] results =  GeocodingApi.geocode(context,
    "1600 Amphitheatre Parkway Mountain View, CA 94043").await();
System.out.println(results[0].formattedAddress);
```

**Comment by rsoffer** [comment]
Hi @chongma @domesticmouse , thanks! I've added the s4j logging part and removed the app engine bit. I'm still seeing 

`java.lang.NoClassDefFoundError: com/google/appengine/api/urlfetch/URLFetchServiceFactory] with root cause
java.lang.ClassNotFoundException: com.google.appengine.api.urlfetch.URLFetchServiceFactory
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1858)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1701)
	at com.google.maps.GaeRequestHandler.<init>(GaeRequestHandler.java:43)`

Without app engine, where is the library supposed to find this dependency? I'm not using Maven so unfortunately I can't simply replicate this test. What are the libraries Maven installed here?

Thanks for your help.

**Comment by rsoffer** [comment]
Nevermind, I got this working. I just built a jar with all dependencies using Maven + your config and included that in my project. Appreciate your help.
