### ISSUE TITLE
App crashing at while getting GeoApiContext

### ISSUE THREAD

**Issue by preetb123** [googlemaps/google-maps-services-java#309]
App crashing at while getting GeoApiContext

```
D/ConnectivityManager.CallbackHandler( 5644): CM callback handler got msg 524290
I/OM.NetworkTransportManager( 5644): onAvailable, Network: 112  
I/PlaceAutocompleteAdapter(19120): Query completed. Received 5 predictions.
W/System.err(19120): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err(19120): SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err(19120): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
D/AndroidRuntime(19120): Shutting down VM
E/AndroidRuntime(19120): FATAL EXCEPTION: main
E/AndroidRuntime(19120): Process: co.goin, PID: 19120
E/AndroidRuntime(19120): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/RateLimiter;
E/AndroidRuntime(19120): 	at com.google.maps.internal.RateLimitExecutorService.<init>(RateLimitExecutorService.java:56)
E/AndroidRuntime(19120): 	at com.google.maps.OkHttpRequestHandler$Builder.<init>(OkHttpRequestHandler.java:96)
E/AndroidRuntime(19120): 	at com.google.maps.GeoApiContext$Builder.<init>(GeoApiContext.java:292)
E/AndroidRuntime(19120): 	at co.goin.HomeActivity.getGeoContext(HomeActivity.java:350)
E/AndroidRuntime(19120): 	at co.goin.HomeActivity.getDirectionsDetails(HomeActivity.java:330)
E/AndroidRuntime(19120): 	at co.goin.HomeActivity.updateViewPort(HomeActivity.java:318)
E/AndroidRuntime(19120): 	at co.goin.HomeActivity.access$800(HomeActivity.java:85)
E/AndroidRuntime(19120): 	at co.goin.HomeActivity$2$2.onSuccess(HomeActivity.java:245)
E/AndroidRuntime(19120): 	at co.goin.HomeActivity$2$2.onSuccess(HomeActivity.java:222)
E/AndroidRuntime(19120): 	at com.google.android.gms.common.api.ResultCallbacks.onResult(Unknown Source)
E/AndroidRuntime(19120): 	at com.google.android.gms.internal.zzbbg.handleMessage(Unknown Source)
E/AndroidRuntime(19120): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19120): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19120): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(19120): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19120): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19120): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(19120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(19120): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.RateLimiter" on path: DexPathList[[zip file "/data/app/co.goin-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(19120): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(19120): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(19120): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(19120): 	... 18 more
E/AndroidRuntime(19120): 	Suppressed: java.lang.ClassNotFoundException: com.google.common.util.concurrent.RateLimiter
E/AndroidRuntime(19120): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(19120): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(19120): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(19120): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(19120): 		... 19 more
E/AndroidRuntime(19120): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager(  911):   Force finishing activity 1 co.goin/.HomeActivity
V/WindowManager(  911): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  911): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
```

the code for `getGeoContext`

```
private GeoApiContext getGeoContext() {

    return new GeoApiContext.Builder()
            .queryRateLimit(1)
            .apiKey(getString(R.string.google_maps_key))
            .connectTimeout(1, TimeUnit.SECONDS)
            .readTimeout(1, TimeUnit.SECONDS)
            .writeTimeout(1, TimeUnit.SECONDS)
            .build();
  }

```

**Comment by domesticmouse** [comment]
I suspect this is related to https://github.com/googlemaps/google-maps-services-java/pull/308

However, I must point out that this library is not designed to be used from Android. Please see [this](https://maps-apis.googleblog.com/2016/09/making-most-of-google-maps-web-service.html) for an explanation as to why you shouldn't be calling our Web Services directly from your mobile application.
