### ISSUE TITLE
Cannot build Jar on Windows

### ISSUE THREAD

**Issue by jshaikh** [googlemaps/google-maps-services-java#326]
I am trying to build Jar on windows using command C:\ .... >gradlew.bat jar however, I keep getting this error,  How can I rectify this problem?

Downloading https://services.gradle.org/distributions/gradle-4.0-all.zip

Exception in thread "main" java.lang.RuntimeException: java.net.ConnectException
: Connection timed out: connect
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAcc
essManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
Caused by: java.net.ConnectException: Connection timed out: connect

**Comment by domesticmouse** [comment]
That's a gradle issue, I'd go ask on [StackOverflow](https://stackoverflow.com/questions/tagged/gradle).
