### ISSUE TITLE
InvalidRequestException with synchronous PlaceApi requests

### ISSUE THREAD

**Issue by StephaneMangin** [googlemaps/google-maps-services-java#340]
Hi guys,

I'm currently facing an issue (bug or miss use of the api) using synchronous PlaceApi requests since my migration from 0.1.2 to 0.2.2 to have icon, photos and all the other stuff in this new version. Better than long words, here it is the code in a spring boot project: 

Implementation of the service :
```
import myObjects.Place;


@Service
public class GooglePlaceSearchService  {

    @Autowired
    private PlaceService placeService;

    private final GeoApiContext context;

    private final SocialsProperties properties;

    @Autowired
    GooglePlaceSearchService(SocialsProperties properties) {
        this.properties = properties;
        context = new GeoApiContext.Builder()
        		.apiKey("my key is currently valid and activated for all map apis")
        		.build();
    }

    /**
     * Create or update a place from google place informations if already exists in database.
     *
     * @param googlePlaceId String
     * @return Place
     */
    //TODO: create a controller to specify google map interaction with place
    public Place convertGooglePlaceToPlace(String googlePlaceId) {
        Place place = placeService.findOneByGoogleplaceId(googlePlaceId);
        if (place == null) {
		try {
		    PlaceDetails result = PlacesApi.placeDetails(context, googlePlaceId).await();
	            place = placeService.create(updateFromGoogleMapResult(new Place(), result));
		} catch (ApiException | InterruptedException | IOException e) {
			e.printStackTrace();
		}
        }
        return place;
    }
...
```

End of the traceback received while printing the stacktrace : 
```
com.google.maps.errors.InvalidRequestException
	at com.google.maps.errors.ApiException.from(ApiException.java:42)
	at com.google.maps.PlaceDetailsRequest$Response.getError(PlaceDetailsRequest.java:80)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:287)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)
	at com.myapp.search.services.GooglePlaceSearchService.convertGooglePlaceToPlace(GooglePlaceSearchService.java:116)
```

If any of you could help it would be great.

Cheers

**Comment by StephaneMangin** [comment]
Problem was miss use. All works well. Great library !
