### ISSUE TITLE
Unable to generate app engine client libraries for Android

### ISSUE THREAD

**Issue by lmgagne** [googlemaps/google-maps-services-java#341]
Any idea why v0.2.2 triggers this error while generating app engine client libraries for Android?

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/maps/GeoApiContext$RequestHandler$Builder
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.api.server.spi.MethodHierarchyReader.buildServiceMethods(MethodHierarchyReader.java:177)
	at com.google.api.server.spi.MethodHierarchyReader.readMethodHierarchyIfNecessary(MethodHierarchyReader.java:50)
	at com.google.api.server.spi.MethodHierarchyReader.getEndpointOverrides(MethodHierarchyReader.java:131)
	at com.google.api.server.spi.config.annotationreader.ApiConfigAnnotationReader.readEndpointMethods(ApiConfigAnnotationReader.java:281)
	at com.google.api.server.spi.config.annotationreader.ApiConfigAnnotationReader.loadEndpointMethods(ApiConfigAnnotationReader.java:66)
	at com.google.api.server.spi.config.ApiConfigLoader.loadConfiguration(ApiConfigLoader.java:76)
	at com.google.api.server.spi.tools.AnnotationApiConfigGenerator.generateConfig(AnnotationApiConfigGenerator.java:59)
	at com.google.api.server.spi.tools.GenApiConfigAction.genApiConfig(GenApiConfigAction.java:85)
	at com.google.api.server.spi.tools.GetClientLibAction.getClientLib(GetClientLibAction.java:76)
	at com.google.api.server.spi.tools.GetClientLibAction.execute(GetClientLibAction.java:55)
	at com.google.api.server.spi.tools.EndpointsTool.execute(EndpointsTool.java:69)
	at com.google.api.server.spi.tools.EndpointsTool.main(EndpointsTool.java:101)
Caused by: java.lang.ClassNotFoundException: com.google.maps.GeoApiContext$RequestHandler$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by lmgagne** [comment]
Nevermind. There was an issue with our gradle.build file where files where in the classpath but not in the /lib folder.

**Comment by domesticmouse** [comment]
I'm curious what you mean by "generating android client libraries for android"? Can you give me some links to the process you are using?

**Comment by lmgagne** [comment]
https://cloud.google.com/endpoints/docs/frameworks/legacy/v1/java/generate-client-libraries-android

The endpoints.sh bash file is expecting all dependencies to be copied under projectDir/lib. I created a new task so that all dependencies are copied at build time. Re-run the endpoints.sh script and everything worked as expected.

**Comment by domesticmouse** [comment]
Thanks!
