### ISSUE TITLE
Add stadium to AddressType

### ISSUE THREAD

**Issue by ben-manes** [googlemaps/google-maps-services-java#364]
Received a log warning due to an unknown mapping.

```
Unknown type for enum com.google.maps.model.AddressType: 'stadium'
at com.google.maps.internal.SafeEnumAdapter.read(SafeEnumAdapter.java:64)
at com.google.maps.internal.SafeEnumAdapter.read(SafeEnumAdapter.java:34)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
```

**Comment by apjanke** [comment]
Could you include the code or URL for a request that will reproduce this warning, so we can verify when it's fixed?

Looks like it may be basically the same issue as #279 and #226.

**Comment by apjanke** [comment]
Never mind; I can reproduce. Using [my gmsj-cli](https://github.com/apjanke/gmsj-cli):

```
$ ./bin/gmsj-cli geocode "Houston Astrodome"
Geocoding: Houston Astrodome
[main] WARN com.google.maps.internal.SafeEnumAdapter - Unknown type for enum com.google.maps.model.AddressType: 'stadium'
Results length: 1
Result 0:
{
```
