### ISSUE TITLE
Getting Java client library to use proxy

### ISSUE THREAD

**Issue by bigalnz** [googlemaps/google-maps-services-java#369]
Hello,

My corporate IT I am pretty sure uses a proxy. Thus I can browse https://maps.googleapis.com but my java program fails to resolve it.

Is there a way to get the instance thats doing me Geocoding to use the proxy if I can get the settings?

A sample would be great.

Thanks

Al

**Comment by domesticmouse** [comment]
Hi Al,

It looks like we have a setter on the configuration to set a Proxy. Have a look at https://github.com/googlemaps/google-maps-services-java/blob/d865b9d2f85d0ad7428f06e8ca15581e15dca853/src/main/java/com/google/maps/OkHttpRequestHandler.java#L138 and tell me if that's enough to get you going.

I haven't worked in an environment that requires proxy setting in over a decade, so I'm unsure how to even test the sample code for that one...

**Comment by bigalnz** [comment]
Thanks domestic mouse. I can try that.

What is the difference between setting the proxy in the OkHttpRequestHandler and setting the JVM one on the command line with something like:

-Dhttp.proxyPort=8080
-Dhttp.proxy=xxx.xxx.xxx.xx 

when you run the jar.

**Comment by domesticmouse** [comment]
I'm unsure what code is dependent on those environment settings. I'd suggest reading up on the OkHTTP documentation to find out what it supports. Thanks!

**Comment by bigalnz** [comment]
I am trying to work out how to use that setter (like on what object to set the proxy, proxy port and username password. I have a

GeoCodingResult instance, GeoApiContext instance, but none of these objects have a proxyAuth getter/setter attached?

**Comment by domesticmouse** [comment]
Try the following. You'll need to configure appropriately for your environment:

```java
package com.google.maps;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.maps.model.GeocodingResult;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.Proxy.Type;

public class Main {

  public static void main(String[] args) throws Exception {
    GeoApiContext context = new GeoApiContext.Builder()
        .apiKey("AIza...")
        .proxy(new Proxy(Type.HTTP, new InetSocketAddress("localhost", 8080)))
        .proxyAuthentication("username", "password")
        .build();
    GeocodingResult[] results =  GeocodingApi.geocode(context,
        "1600 Amphitheatre Parkway Mountain View, CA 94043").await();
    Gson gson = new GsonBuilder().setPrettyPrinting().create();
    System.out.println(gson.toJson(results[0].addressComponents));

  }

}
```

**Comment by bbasumatary** [comment]
Stuck on the same issue .. we have  proxy for https (8081) and  http (8080). 



GeoApiContext context = new GeoApiContext.Builder()
				.proxy(new Proxy(Type.HTTP, new InetSocketAddress("******************", 8081)))
				.proxyAuthentication("***", "****************")
				.apiKey("AI*****").build();
		
		
		LatLng location = new LatLng(40.714728, -73.998672);
		ElevationResult results;
		try {
			results = ElevationApi.getByPoint(context, location).await();
			System.out.println("Elevation : " + results.elevation);
			Gson gson = new GsonBuilder().setPrettyPrinting().create();
			logger.info(gson.toJson(results));
		} catch (ApiException | InterruptedException | IOException e) {
			e.printStackTrace();
		}


 I get the following message !!!!!! - -- whereas (sometimes only ) without the proxy settings i get result.  then back to same  certificate issue.   Any help ?

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 31 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 37 more
