### ISSUE TITLE
Using the client library in a Google App Engine project

### ISSUE THREAD

**Issue by theyann** [googlemaps/google-maps-services-java#47]
Hello guys,

I am working on a GAE backend which requires the DistanceMatrixAPI.
I am doing TDD, thus I've build my code and classes with tests first, and all the tests pass. Now I fire up my GAE server locally, and I have the following stack:
```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" 
"modifyThreadGroup")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkAccess(DevAppServerFactory.java:454)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:389)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:460)
	at com.google.maps.internal.RateLimitExecutorService.<init>(RateLimitExecutorService.java:55)
	at com.google.maps.GeoApiContext.setQueryRateLimit(GeoApiContext.java:224)
	at com.google.maps.GeoApiContext.setQueryRateLimit(GeoApiContext.java:210)
	at com.google.maps.GeoApiContext.<init>(GeoApiContext.java:56)
	at com.techyos.jardibox.service.GoogleServicesHelper.requestDistances(GoogleServicesHelper.java:39)
	at com.techyos.jardibox.service.ArchitectService.getMissingDistancesFromGoogleServices(ArchitectService.java:136)
	at com.techyos.jardibox.service.ArchitectService.calculateDistances(ArchitectService.java:130)
	at com.techyos.jardibox.service.ArchitectService.getAllDto(ArchitectService.java:73)
	at com.techyos.jardibox.service.RegistrationService.mapDomainsToArchitects(RegistrationService.java:136)
	at com.techyos.jardibox.service.RegistrationService.stepGetArchitects(RegistrationService.java:89)
	at com.techyos.jardibox.controller.api.RegistrationApiController.stepGetArchitects(RegistrationApiController.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:115)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:690)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:876)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:491)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

My GoogleServiceHelper method looks like this:
```
  public DistanceMatrix requestDistances(List<String> from, List<String> to) {
    GeoApiContext context = new GeoApiContext().setApiKey(config.getGoogleApiKey());

    try {
      return DistanceMatrixApi.getDistanceMatrix(context,
          from.toArray(new String[from.size()]),
          to.toArray(new String[to.size()]))
          .mode(TravelMode.DRIVING).await();
    } catch (Exception e) {
      logger.error("An error occured", e);
    }

    return null;
  }
```

And the crash occures at the initialization of the GeoApiContext.

Is there a quick fix for this or am I just not supposed to use this client library in Google App Engine?

Thanks a lot in advance.

**Comment by BenjaminMercier19** [comment]
Hi,

Does your implementation of URLFetch worked for this library @theyann ? Cause I haven't seen any pull request about this, yet.
Is there any info about that or should I try something with URLFetch ?

Thanks for the work !

**Comment by theyann** [comment]
No finally I did not use this lib. I ended only extracting the objects, but I re-created the urls and used url fetch in my own code. I wasn't planning to make any kind of pull request as, if it was to become a library, it would be quite different.

**Comment by BenjaminMercier19** [comment]
Ok thanks for the quick answser !

**Comment by broady** [comment]
As you all found out - it's not trivial to get this library working with AppEngine. We'd need to abstract the transport so that it could be switched between okhttp and urlfetch. Async calls would also not be supported on AppEngine due to lack of support for starting threads.

If anyone wants to have a go at abstracting out the transport, that'd be a welcome contribution.

**Comment by ZiglioNZ** [comment]
I've done this kind of s&*t work in the past, but this one is or tied up to this OkHttpClient I've never heard about. See for example:
https://github.com/forcedotcom/wsc/blob/master/src/main/java/com/sforce/ws/transport/GaeHttpTransport.java

**Comment by tbdevel** [comment]
I tried changing the library a bit today in order to make it work on GAE, but it's too tied with OkHttp to get this done quickly. I ended up in just using the classes in /model for parsing with GSON and creating the request manually.

**Comment by ZiglioNZ** [comment]
Have you tried https://github.com/googlemaps/google-maps-services-java/pull/85 @tbdevel 
It kind of works

**Comment by JavierAriasGonzalez** [comment]
I have tried tried #85 and it works like a charm. Thanks ZiglioNZ for the work.

**Comment by domesticmouse** [comment]
I've just released v0.1.14 of the client library, now with GAE support. There is a one line code change required to change the way HTTP requests are made across to the GAE supported API. Version 0.1.14 should appear on [search.maven.org](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.maps%22%20AND%20a%3A%22google-maps-services%22) in the next couple of hours.

**Comment by mazook** [comment]
Just to clarify, the code below still launches a thread? Is there a particular way to call the service request in AppEngine to prevent this?

```
GeoApiContext context = new GeoApiContext().setApiKey(...key);
GeocodingApiRequest r = GeocodingApi.reverseGeocode(context, new LatLng(...,...));
r.await();
```

**Comment by domesticmouse** [comment]
@mazook that looks like a bug. Can you raise a new issue plz?

**Comment by rafaelgom3s** [comment]
@Koozamo : probably you already figured out, but for others coming across with the same issue here is the solution that worked for me:
```java
GeoApiContext context = new GeoApiContext(new GaeRequestHandler()).setApiKey(...key);
GeocodingApiRequest r = GeocodingApi.reverseGeocode(context, new LatLng(...,...));
r.await();
```

**Comment by Koozamo** [comment]
@rafaelgom3s 👍  thanks for the pointer. I was missing the request handler as you have shown. I will close the issue that I had created.

**Comment by wildcherrycandy** [comment]
Solution for latest version:
`new GeoApiContext.Builder(new GaeRequestHandler.Builder()).apiKey(googleApiKey).build();`

But NOT:
`new GeoApiContext.Builder().requestHandlerBuilder(new GaeRequestHandler.Builder()).apiKey(googleApiKey).build();`
