### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime"

### ISSUE THREAD

**Issue by chnaveen138** [googlemaps/google-maps-services-java#509]
Found that java.time package is only available for API >= 26.
So please tell me how to handle this error for API < 26

**I am getting this error while fetching directions:**
//////////////////////////////////////////////////////////////////////
```
10-30 18:41:56.897 31681-31832/com.codingwithmitch.googlemaps2018 E/AndroidRuntime: FATAL EXCEPTION: Rate Limited Dispatcher
    Process: com.codingwithmitch.googlemaps2018, PID: 31681
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:241)
        at com.google.maps.internal.OkHttpPendingResult.onResponse(OkHttpPendingResult.java:207)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime" on path: DexPathList[[zip file "/data/app/com.codingwithmitch.googlemaps2018-1/base.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.codingwithmitch.googlemaps2018-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.codingwithmitch.googlemaps2018-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:241) 
        at com.google.maps.internal.OkHttpPendingResult.onResponse(OkHttpPendingResult.java:207) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```
///////////////////////////////////////////////////////////

**My Code:**

```
private void calculateDirections(Marker marker){
        Log.d(TAG, "calculateDirections: calculating directions.");
        com.google.maps.model.LatLng destination = new com.google.maps.model.LatLng(
                marker.getPosition().latitude,
                marker.getPosition().longitude
        );
        DirectionsApiRequest directions = new DirectionsApiRequest(mGeoApiContext);
        directions.alternatives(true);
        directions.origin(
                new com.google.maps.model.LatLng(
                        currentUserLocation.getGeoPoint().getLatitude(),
                        currentUserLocation.getGeoPoint().getLongitude()
                )
        );
        Log.d(TAG, "calculateDirections: destination: " + destination.toString());
        directions.destination(destination).setCallback(new PendingResult.Callback<DirectionsResult>() {
            @Override
            public void onResult(DirectionsResult result) {
                Log.d(TAG, "calculateDirections: routes: " + result.routes[0].toString());
                Log.d(TAG, "calculateDirections: duration: " + result.routes[0].legs[0].duration);
                Log.d(TAG, "calculateDirections: distance: " + result.routes[0].legs[0].distance);
                Log.d(TAG, "calculateDirections: geocodedWayPoints: " + result.geocodedWaypoints[0].toString());
            }
            @Override
            public void onFailure(Throwable e) {
                Log.e(TAG, "calculateDirections: Failed to get directions: " + e.getMessage() );

            }
        });
    }
```

**Comment by apjanke** [comment]
When you say "API >= 26", are you talking about the Android API level?

**Comment by chnaveen138** [comment]
Yes! It's about Android API Level.  When I am trying in Emulator whose API Level is 27 it's working fine... But in emulator whose API Level is 24, it gives me that error.

**Comment by chnaveen138** [comment]
> When you say "API >= 26", are you talking about the Android API level?



> When you say "API >= 26", are you talking about the Android API level?

Yes! It's about Android API Level. When I am trying in Emulator whose API Level is 27 it's working fine... But in emulator whose API Level is 24, it gives me that error.

**Comment by chnaveen138** [comment]
> When you say "API >= 26", are you talking about the Android API level?

Yes! It's about Android API Level. When I am trying in Emulator whose API Level is 27 it's working fine... But in emulator whose API Level is 24, it gives me that error.

**Comment by chnaveen138** [comment]
> Same problem after i upgraded to version 0.9.0

It made me to rollback to 0.2.11 and it's working fine...

**Comment by domesticmouse** [comment]
Please don't use this client library on Android. It opens you up to third parties stealing your API Key.
