### ISSUE TITLE
Cannot allocate class com.google.maps.model.LatLng

### ISSUE THREAD

**Issue by paulbakker** [googlemaps/google-maps-services-java#54]
The LatLng class doesn't have a no-arg constructor, and gson can't handle this. The following exception is thrown:

```
Caused by: java.lang.RuntimeException: Unable to invoke no-args constructor for class com.google.maps.model.LatLng. Register an InstanceCreator with Gson for this type may fix this problem.
    at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:210)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:186)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
    at com.google.gson.Gson.fromJson(Gson.java:810)
    at com.google.gson.Gson.fromJson(Gson.java:748)
    at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:222)
    at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:155)
    at com.google.maps.PendingResultBase.await(PendingResultBase.java:55)
```

The problem appears as soon as the location information of a geo request is accessed:

```
GeocodingResult[] geo = GeocodingApi.geocode(context, "Some address").await();
System.out.println(geo[0].geometry.location.lat);
```

**Comment by broady** [comment]
Sweet! Thanks for checking :)

**Comment by snotling** [comment]
@paulbakker: you saved my day!
My problem was absolutely not related to Google Maps -- I was using GSON in a Wildfly module, which also requires explicitly exporting the "sun.misc" package.

**Comment by nramanath** [comment]
@paulbakker - can you please elaborate on your solution, I am facing the same issue and I don't understand this part of your solution "After exporting the sun.misc package it all works." 

My problem is exactly as mentioned in #218 

Thank you.
