### ISSUE TITLE
Crash on version 0.9.1 when calling the API

### ISSUE THREAD

**Issue by yuliuslionardi** [googlemaps/google-maps-services-java#544]
01-21 16:57:33.720 20671-20744/com.project.android.argapro E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.project.android.argapro, PID: 20671
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZonedDateTime;
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:241)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.PendingResultBase.await(PendingResultBase.java:58)
        at com.project.android.argapro.main.demobooker.maps.MapFragmentActivity$getLocationDetails$1.invokeSuspend(MapFragmentActivity.kt:163)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.ZonedDateTime" on path: DexPathList[[zip file "/data/app/com.project.android.argapro-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:241) 
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176) 
        at com.google.maps.PendingResultBase.await(PendingResultBase.java:58) 
        at com.project.android.argapro.main.demobooker.maps.MapFragmentActivity$getLocationDetails$1.invokeSuspend(MapFragmentActivity.kt:163) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
        Suppressed: java.lang.ClassNotFoundException: java.time.ZonedDateTime
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 10 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Hi I'm using version 0.9.1 and Android 5.0.1 and got this issue, but when I revert it back to version 0.2.11 which was still using LocalDateTime instead of ZonedDateTime it works fine. Is this expected? I've tried on several devices and it seems device that has OS below level 26 got this issue too. Thank you

**Comment by domesticmouse** [comment]
Android is explicitly not supported by this library. Please see the disclaimer in intended usage section of the [README](https://github.com/googlemaps/google-maps-services-java/blob/master/README.md#intended-usage-of-this-library). Thanks!

**Comment by magesh1996** [comment]
then how to use directions api in android?

**Comment by domesticmouse** [comment]
@magesh1996 please see [the project README](https://github.com/googlemaps/google-maps-services-java#intended-usage-of-this-library) for details on preferred approach.

**Comment by CaptainParanoid** [comment]
implementation group: 'com.github.seratch', name: 'java-time-backport', version: '1.0.0'

**Comment by CaptainParanoid** [comment]
Add this library to gradle 
implementation group: 'com.github.seratch', name: 'java-time-backport', version: '1.0.0'

**Comment by CaptainParanoid** [comment]
> then how to use directions api in android?

implementation group: 'com.github.seratch', name: 'java-time-backport', version: '1.0.0'

**Comment by darja** [comment]
@CaptainParanoid Just faced this issue and your answer helped. Thank you!

**Comment by pablorcruh** [comment]
Thanks @CaptainParanoid your answer helped me

**Comment by rdfreitas** [comment]
Thanks @CaptainParanoid

**Comment by xlan-codes** [comment]
> Add this library to gradle
> implementation group: 'com.github.seratch', name: 'java-time-backport', version: '1.0.0'

you saved my life

**Comment by neha737** [comment]
> implementation group: 'com.github.seratch', name: 'java-time-backport', version: '1.0.0'

thank you so much. my issue is resolved now.

**Comment by CaptainParanoid** [comment]
> Add this library to gradle 
> implementation group: 'com.github.seratch', name: 'java-time-backport', version: '1.0.0'

Actually it is not a good idea to do this on a production application, however for college projects or hobby projects this is fine. It will saves you time on setting up a server.

**Comment by neha737** [comment]
then, whats the  solution?

**Comment by CaptainParanoid** [comment]
> then, whats the  solution?
> 

You will have to setup a server, setup an api and make android app use that api instead of directly using the maps api. This package is meant for server application that's why it doesn't directly work with android.
