### ISSUE TITLE
java.lang.ClassNotFoundException: okhttp3.Authenticator not found when wrapped into OSGI bundle and deployed to OSGI environment

### ISSUE THREAD

**Issue by fg78nc** [googlemaps/google-maps-services-java#551]
Getting java.lang.ClassNotFoundException: okhttp3.Authenticator not found when wrapped into OSGI bundle and deployed to OSGI environment.

```
Caused by: java.lang.ClassNotFoundException: okhttp3.Authenticator not found by wrap_mvn_com.google.maps_google-maps-services_0.9.2 [1180]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by domesticmouse** [comment]
I don't know anything about the requirements for shipping dependencies for OSGI. I do, however, accept Pull Requests. =)

**Comment by jpoehnelt** [comment]
@fg78nc I am going to close this with a link to the [StackOverflow discussion](https://stackoverflow.com/questions/55073306/osgi-maven-wrapped-bundle-throws-java-lang-classnotfoundexception-if-it-tries) about this issue. Let me know if there is something we can change on our end!
