### ISSUE TITLE
JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 4294967295 at line 289 column 41 path $.routes[0].waypoint_order[0]

### ISSUE THREAD

**Issue by nguyetv75** [googlemaps/google-maps-services-java#574]
We just started getting the following exception below from Google's direction API.  Has anyone encountered this issue?

com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 4294967295 at line 289 column 41 path $.routes[0].waypoint_order[0]
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:272)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:177)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)

**Comment by apjanke** [comment]
Sounds like maybe the `public int[] waypointOrder` field in `com.google.maps.model.DirectionsRoute` needs to be an `unsigned int` or `long`? Can you provide an example of a query that reproduces this?

**Comment by apjanke** [comment]
BTW, that's a heck of a lot of waypoints – as I understand it from [the API doco](https://developers.google.com/maps/documentation/directions/intro), `waypoint_order` contains a list of indexes into the supplied? waypoints list. If you're getting 4294967295 there, that implies that there are 2^32 waypoints in your route request?!? (4294967295 is a suspicious number because it's the max value for an unsigned 32-bit int.) Maybe this is (also) actually a bug on the server side, with a 32-bit unsigned int wraparound error?

**Comment by cdandoy** [comment]
Here is an example of a request that failed 20 minutes ago, only 2 waypoints, the same request works fine now.
https://maps.googleapis.com/maps/api/directions/json?key=xxxx&origin=39.43546890,-76.80062610&destination=39.43546890,-76.80062610&waypoints=39.44081090,-76.80682870|39.42602700,-76.84214290

We do ~40k direction requests per day and 50 failed yesterday with that error. The issue started on the 17th at 4PM central.

**Comment by amuramoto** [comment]
@cdandoy any recurring incidence of this?

**Comment by cdandoy** [comment]
No, it stopped, the last occurrence was on the 20th.
Thank you.

**Comment by amuramoto** [comment]
Ok, I'm going to close, but please ping or open a new issue if you see it recur. Thanks for reporting!
