### ISSUE TITLE
okhttp 2.0.0 dependency on Java 7 forces me to use Java 7 as well

### ISSUE THREAD

**Issue by lsli** [googlemaps/google-maps-services-java#65]
This project indicates that Java 6 is minimally required (and is specified in the Gradle dependcies), but the project's dependency on okhttp 2.0 (which is compiled on Java 7) effectively makes this project require Java 7 in my server environment.  I tried modifying the Gradle dependencies to indicate a dependency on okhttp 1.6.0 (which is the latest okhttp version that uses Java 6), but then the project couldn't compile (with 27 or so compile errors) probably because of the API changes in okhttp 1.6.0 to 2.0.0.  I tried this on the v0.1.5 maintenance release tag and also the latest code - and all your old code when I looked at the tags all the way back to v0.1.1 requires okhttp 2.0 as well.

As proof, when I compile with JDK 6:

./gradlew jar
:updateVersion
:compileJava
warning: com/squareup/okhttp/Dispatcher.class(com/squareup/okhttp:Dispatcher.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: com/squareup/okhttp/OkHttpClient.class(com/squareup/okhttp:OkHttpClient.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: com/squareup/okhttp/Request.class(com/squareup/okhttp:Request.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: com/squareup/okhttp/Call.class(com/squareup/okhttp:Call.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: com/squareup/okhttp/Callback.class(com/squareup/okhttp:Callback.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: com/squareup/okhttp/Response.class(com/squareup/okhttp:Response.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: com/squareup/okhttp/Request$Builder.class(com/squareup/okhttp:Request$Builder.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: com/squareup/okhttp/ResponseBody.class(com/squareup/okhttp:ResponseBody.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
8 warnings
:processResources UP-TO-DATE
:classes
:jar

Then when I run the tests:

./gradlew test
:updateVersion UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
Note: /home/myhome/workspace/google-maps-services-java/src/test/java/com/google/maps/GeoApiContextTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processTestResources UP-TO-DATE
:testClasses
:test

com.google.maps.GeoApiContextTest > testErrorResponseRetries FAILED
    java.lang.UnsupportedClassVersionError at GeoApiContextTest.java:42

com.google.maps.GeoApiContextTest > testRetryCanBeDisabled FAILED
    java.lang.UnsupportedClassVersionError at GeoApiContextTest.java:42

com.google.maps.GeoApiContextTest > testRetryEventuallyReturnsTheRightExceptionFAILED
    java.lang.UnsupportedClassVersionError at GeoApiContextTest.java:42

com.google.maps.GeoApiContextTest > testGetIncludesDefaultUserAgent FAILED
    java.lang.UnsupportedClassVersionError at GeoApiContextTest.java:42

com.google.maps.ElevationApiTest > testGetByPointsThrowsRequestDeniedExceptionFromResponse                                                                     FAILED
    java.lang.UnsupportedClassVersionError at ElevationApiTest.java:35

com.google.maps.ElevationApiTest > testGetByPointThrowsInvalidRequestExceptionFromResponse                                                                     FAILED
    java.lang.UnsupportedClassVersionError at ElevationApiTest.java:35

com.google.maps.DistanceMatrixApiTest > testTravelModeRejectsInvalidMode FAILED
    java.lang.UnsupportedClassVersionError at DistanceMatrixApiTest.java:37

com.google.maps.DistanceMatrixApiTest > testLatLngOriginDestinations FAILED
    java.lang.UnsupportedClassVersionError at DistanceMatrixApiTest.java:37

com.google.maps.DistanceMatrixApiIntegrationTest > initializationError FAILED
    java.lang.IllegalArgumentException

com.google.maps.DirectionsApiTest > initializationError FAILED
    java.lang.IllegalArgumentException

com.google.maps.TimeZoneApiTest > initializationError FAILED
    java.lang.IllegalArgumentException

com.google.maps.ElevationApiIntegrationTest > initializationError FAILED
    java.lang.IllegalArgumentException

com.google.maps.GeocodingApiTest > initializationError FAILED
    java.lang.IllegalArgumentException

19 tests completed, 13 failed, 1 skipped
:test FAILED

FAILURE: Build failed with an exception.

This is probably a request that may be ignored, but could you modify the code to have a dependency on okhttp 1.6.0 instead?

**Comment by markmcd** [comment]
OkHttp's dependency on Java 6 is only at compile-time, so you don't need to upgrade your server environment. Check out the thread on their repository for more detail: https://github.com/square/okhttp/issues/528

**Comment by lsli** [comment]
Thanks for the quick reply and for the info on the thread.  However, are you sure it's only a compile time dependency?  It seems like there's a runtime dependency on okhttp based on the methods I'm calling via my test class.  Here's my TestNG test class - just to see if it would work on my environment and during run time.  I've adapted it slightly from your Geocoding unit test:

@BeforeTest
	public void setUp() throws Exception {
		context = new GeoApiContext().setApiKey(googleApiKey);
		context.setQueryRateLimit(3).setConnectTimeout(1, TimeUnit.SECONDS)
				.setReadTimeout(1, TimeUnit.SECONDS)
				.setWriteTimeout(1, TimeUnit.SECONDS);
	}

	@Test
	public void testSimpleGeocode() throws Exception {
		GeocodingResult[] results = GeocodingApi.newRequest(context)
				.address("Sydney").await();
		checkSydneyResult(results);
	}

	private void checkSydneyResult(GeocodingResult[] results) {
		assertNotNull(results);
		assertNotNull(results[0].geometry);
		assertNotNull(results[0].geometry.location);
		assertEquals(-33.8674869, results[0].geometry.location.lat, EPSILON);
		assertEquals(151.2069902, results[0].geometry.location.lng, EPSILON);
		assertEquals(LocationType.APPROXIMATE, results[0].geometry.locationType);
	}

I then get the following error when running the test in the setUp method:

java.lang.NoClassDefFoundError: com/squareup/okhttp/OkHttpClient
	at com.google.maps.GeoApiContext.<init>(GeoApiContext.java:49)
	at mypackage.test.action.googleapis.maps.GoogleMapsGeocodingQueryTest.setUp(GoogleMapsGeocodingQueryTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.OkHttpClient
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 24 more

OK, so based on the methods I call in my test class (unless these are not the recommended methods to use), then I need to have the okhttp library in my classpath.  Of course, once I put the okhttp 2.0.0 library in my classpath, I immediately get the Java 7/Java 6 conflict error:

FAILED CONFIGURATION: @BeforeTest setUp
java.lang.UnsupportedClassVersionError: com/squareup/okhttp/OkHttpClient : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at com.google.maps.GeoApiContext.<init>(GeoApiContext.java:49)
	at mypackage.test.action.googleapis.maps.GoogleMapsGeocodingQueryTest.setUp(GoogleMapsGeocodingQueryTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

SKIPPED: testSimpleGeocode

**Comment by markmcd** [comment]
Oh - I see now. The OkHttp binary distribution is compiled against JDK7. They claim it's JDK6 compatible but that's only because the Android runtime (Java level 6) loads JDK7 classes without issue.

Unfortunately the solution for us is to revert our advertised platform support to Java 7, in line with [OkHttp's](http://square.github.io/okhttp/).

**Comment by lsli** [comment]
Thanks for the clarification.  I'm not familiar with okhttp.  But would it be difficult for you or anyone to revert to using okhttp 1.6.0 instead of 2.0.0?  Is that an option you would be willing to look at or is it just too complicated (or unwilling because of the 2.0.0 features) to modify the code to do this?

**Comment by fcamblor** [comment]
I would definitely put a :+1: on providing java 1.6 support for google-maps-services

**Comment by domesticmouse** [comment]
I'm curious why the desire for Java 6 support - it is no longer supported by Oracle (as of February 2013) - and thus is a security risk in production. Heck, Java 7 is going to be end of life'd in April this year.

**Comment by lsli** [comment]
I can't speak for others, but unfortunately it's just business requirements - where there's no funding to move away from running IceFaces 1.8/Seam 2.2/JSF 1.2/Liferay 6 on JBoss 5.0.1 server - at least for now.  Yes, I understand that's not an "ideal" answer, but it's reality - at least for me.

**Comment by joshes** [comment]
In the same boat. Enterprise use case, can't upgrade to 7 at present time.

**Comment by bluebery** [comment]
I forked away and was able to build both okhttp and okio with java 1.6. Like some of you have said it is mostly just the diamond operator but a few other small things. 

I haven't gone through and updated the test classes to compile with 1.6, so it will generate errors when trying to build the tests during an `mvn clean test` sequence.

okhttp 2.3.0 / okio 1.3.0

https://github.com/bluebery/okhttp
https://github.com/bluebery/okio

**Comment by domesticmouse** [comment]
I'm not planning on supporting Java 1.6 in this library, but if someone has a 1.6 compatible fork they are maintaining, please let us know. Thanks!
