### ISSUE TITLE
ClassNotFoundException okio.Sink

### ISSUE THREAD

**Issue by TheRootDeveloper01** [googlemaps/google-maps-services-java#68]
What package is okio.Sink?
I get this while trying your example shown in the readme.
<code>
Exception in thread "Rate Limited Dispatcher" java.lang.NoClassDefFoundError: okio/Sink
	at com.squareup.okhttp.Call.getResponse(Call.java:252)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
	at com.squareup.okhttp.Call.access$100(Call.java:34)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:156)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ClassNotFoundException: okio.Sink
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
</code>
I already implemented gson and okhttp.
Any suggestions?
Thank you.

**Comment by TheRootDeveloper01** [comment]
No worries, just a grandle error.

**Comment by kco0910** [comment]
download okio import 
http://search.maven.org/#browse%7C-705824285
