### ISSUE TITLE
ClassNotFoundException: Didn't find class "java.time.ZonedDateTime"

### ISSUE THREAD

**Issue by tirumala007** [googlemaps/google-maps-services-java#726]
my code to get direction from two positions, i am getting NoClassDefFoundError

api 23 marshmallow
repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.maps:google-maps-services:0.18.0'
    implementation 'org.slf4j:slf4j-simple:1.7.25'
}

         private fun calculateDirections(marker: Marker?) {
                           try{
            val directions = DirectionsApiRequest(mGeoApiContext)
            directions.alternatives(true)
             val destination = com.google.maps.model.LatLng(
                     marker!!.position.latitude,
                     marker!!.position.longitude
             )
         directions.origin(
                 com.google.maps.model.LatLng(
                         userLat,
                         userLon)g)
          directions.destination(destination).
         setCallback(object : PendingResult.Callback<DirectionsResult?> {
             override fun onResult(result: DirectionsResult?) {
                 Toast.makeText(this@GetDirectionsForLocationActivity, "successfull loading the routes dudes", Toast.LENGTH_SHORT).show()

                 addPolylinesToMap(result!!)
             }

             override fun onFailure(e: Throwable) {
                 Toast.makeText(this@GetDirectionsForLocationActivity, "error while retreiving routes dude", Toast.LENGTH_SHORT).show()

                 Log.e(TAG, "calculateDirections: Failed to get directions: " + e.message)
             }

         })

        } catch (e: Exception)
        {
            Toast.makeText(this@GetDirectionsForLocationActivity, "try catch here", Toast.LENGTH_SHORT).show()

        }
    }

 adding polylines

    private fun addPolylinesToMap(result: DirectionsResult?) {
        Handler(Looper.getMainLooper()).post(Runnable {
            for (route in result!!.routes) {
                val decodedPath = PolylineEncoding.decode(route.overviewPolyline.encodedPath)
                val newDecodedPath: MutableList<LatLng> = ArrayList()

                for (latLng in decodedPath) {
                    newDecodedPath.add(LatLng(
                            latLng.lat,
                            latLng.lng
                    ))
                }
                val polyline: Polyline = mMap.addPolyline(PolylineOptions().addAll(newDecodedPath))
                polyline.color = ContextCompat.getColor(this@GetDirectionsForLocationActivity, R.color.darkGrey)
                polyline.isClickable = true
            }
        })
    }

my logcat;

04-05 17:33:45.732 11023-11186/com.hema.anonymousinfo E/AndroidRuntime: FATAL EXCEPTION: Rate Limited Dispatcher
    Process: com.hema.anonymousinfo, PID: 11023
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZonedDateTime;
        at com.google.maps.internal.OkHttpPendingResult.parseResponseInternal(OkHttpPendingResult.java:266)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:230)
        at com.google.maps.internal.OkHttpPendingResult.onResponse(OkHttpPendingResult.java:219)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.ZonedDateTime" on path: DexPathList[[zip file "/data/app/com.hema.anonymousinfo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hema.anonymousinfo-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.maps.internal.OkHttpPendingResult.parseResponseInternal(OkHttpPendingResult.java:266) 
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:230) 
        at com.google.maps.internal.OkHttpPendingResult.onResponse(OkHttpPendingResult.java:219) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: java.time.ZonedDateTime
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 9 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by mortenholmgaard** [comment]
@tirumala007 I have the same issue - how did you solve it?
