### ISSUE TITLE
Application will not load in android 11 when trying to use suggested sdk.

### ISSUE THREAD

**Issue by Ramnathpraveen** [googlemaps/google-maps-services-java#735]
In Android when trying to do the suggested implementation. the application gets crashed on load for android 11. works fine with all other versions of android

**Comment by rwaldura** [comment]
are you getting the error:

```
    java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform.get(Platform.java:85)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.google.maps.OkHttpRequestHandler$Builder.build(OkHttpRequestHandler.java:201)
        at com.google.maps.GeoApiContext$Builder.build(GeoApiContext.java:625)
        (...)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30

```

**Comment by rwaldura** [comment]
My workaround was to target Android 10 instead — granted, a mere workaround.
In app ``build.gradle``:
``targetSdkVersion 29``
