### ISSUE TITLE
ClassNotFoundException: com.google.appengine.api.urlfetch.URLFetchServiceFactory (Java 11, App Engine)

### ISSUE THREAD

**Issue by bashoogzaad** [googlemaps/google-maps-services-java#745]
I am currently migrating App engine from java 8 to java 11, and I get the following error: 

`java.lang.ClassNotFoundException: com.google.appengine.api.urlfetch.URLFetchServiceFactory at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at com.google.maps.GaeRequestHandler.(GaeRequestHandler.java:47) at com.google.maps.GaeRequestHandler$Builder.build(GaeRequestHandler.java:166) at com.google.maps.GeoApiContext$Builder.build(GeoApiContext.java:625)`

The App Engine SDK is not available for java 11, so I think this is causing the error.

Is there any way to make this library work on Java 11 App Engine?

Any help is greatly appreciated!

**Comment by chdlsp** [comment]
![image](https://user-images.githubusercontent.com/44944612/137265737-41f07919-657e-4605-9b99-5e544891fa32.png)

I don't this it is problem with the SDK version.
Instead, I guess this problem is from Gradle or IDE something but I cannot still figure it out.

Anyway, this problem will be fixed soon whatever the problem is from.

**Comment by chdlsp** [comment]
@bashoogzaad After add appengine library, It works well :) Thank you!
