### ISSUE TITLE
Nearby search request with tokenpage not working

### ISSUE THREAD

**Issue by franrolando** [googlemaps/google-maps-services-java#775]
#### Environment details

1. Places API
2. Win 10 64 bits (Local testing)
3. Java dependency version 1.0.1v. Spring boot 2.5.5.

#### Steps to reproduce

  1.  Execute the code below.

#### Code example

```
@Autowired
	private GeoApiContext geoContext;

	@Override
	public List<PlacesSearchResult> getPharmacies(double lat, double lng) {
		LatLng latLng = new LatLng(lat, lng);
		List<PlacesSearchResult> pharmacies = new ArrayList<>();
		NearbySearchRequest nearbySearch = PlacesApi.nearbySearchQuery(geoContext, latLng).type(PlaceType.PHARMACY)
				.rankby(RankBy.DISTANCE);
		try {
			PlacesSearchResponse response = nearbySearch.await();
			List<PlacesSearchResult> pharmaciesRaw = Arrays.stream(response.results).collect(Collectors.toList());
			pharmacies.addAll(pharmaciesRaw);
			while (response.nextPageToken != null) {
				nearbySearch = PlacesApi.nearbySearchNextPage(geoContext, response.nextPageToken);
				response = nearbySearch.await();
				pharmaciesRaw = Arrays.stream(response.results).collect(Collectors.toList());
				pharmacies.addAll(pharmaciesRaw);
			}
		} catch (ApiException | InterruptedException | IOException e) {
			e.printStackTrace();
		}
		return pharmacies;
	}
```

#### Stack trace

Inside the while loop the code throws the following exception, but if you debug the code and let pass a few seconds between await() invocations the code works well
```
com.google.maps.errors.InvalidRequestException
	at com.google.maps.errors.ApiException.from(ApiException.java:42)
	at com.google.maps.NearbySearchRequest$Response.getError(NearbySearchRequest.java:227)
	at com.google.maps.internal.OkHttpPendingResult.parseResponseInternal(OkHttpPendingResult.java:316)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:230)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:184)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:61)
	at com.teqstream.tsbslogic.healthcase.service.GoogleService.getPharmacies(GoogleService.java:49)
	at com.teqstream.tsbslogic.healthcase.service.HospitalService.getHospitals(HospitalService.java:30)
	at com.teqstream.tsbslogic.healthcase.controller.HospitalsController.getHospitals(HospitalsController.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks!

**Comment by franrolando** [comment]
Is because google's license terms don't allow you to fetch all the results at once and return them all at once to the user. You should have a user action asking for more results, which adds a delay of a couple of seconds.
