### ISSUE TITLE
NumberFormatException when parsing SpeedLimit response for nonmetric countries.

### ISSUE THREAD

**Issue by gitbrantley** [googlemaps/google-maps-services-java#87]
I am getting a NumberFormatException when requesting speed limits within the USA. The API specifies the speedLimit property to be in kilometers per hour, so a float must be returned to provide a decent amount of accuracy when converted in miles per hour.

It as simple as changing `com.google.maps.model.SpeedLimit`'s speedLimit property from a `long` to a `double`. I can provide a pull request if needed.

### Example Test
```java
  @Test
  public void testSpeedLimitsWithUSALatLngs() throws Exception {
    SpeedLimit[] speeds = RoadsApi.speedLimits(context,
        new LatLng(28.361803, -81.518966),
        new LatLng(33.777622, -84.397788),
        new LatLng(40.758810, -73.984928),
        new LatLng(38.907472, -77.036525),
        new LatLng(37.682462, -97.332222),
        new LatLng(37.420978, -122.084389),
        new LatLng(33.809636, -117.915440)).await();

    assertNotNull(speeds);
    assertEquals(7, speeds.length);

    for (SpeedLimit speed : speeds) {
      assertNotNull(speed.placeId);
      assertTrue(speed.speedLimit > 0);
    }
  }
```

### Stack Trace

`com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 56.327042 at line 5 column 30 path $.speedLimits[0].speedLimit
	at com.google.gson.internal.bind.TypeAdapters$8.read(TypeAdapters.java:263)
	at com.google.gson.internal.bind.TypeAdapters$8.read(TypeAdapters.java:253)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:217)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.RoadsApiIntegrationTest.testSpeedLimitsWithUSALatLngs(RoadsApiIntegrationTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NumberFormatException: Expected a long but was 56.327042 at line 5 column 30 path $.speedLimits[0].speedLimit
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:980)
	at com.google.gson.internal.bind.TypeAdapters$8.read(TypeAdapters.java:261)
	... 45 more
`

**Comment by markmcd** [comment]
Ahh, I thought we found all of these! I'd love it if you could send a PR through.

Thanks

**Comment by domesticmouse** [comment]
This appears to have been fixed.

**Comment by viswakumar** [comment]
Ahh, I thought we found all of these! I'd love it if you could send a PR through.

Thanks
